### ISSUE TITLE
Filter data based on custom scoped_resource

### ISSUE THREAD

**Issue by rslhdyt** [SourceLabsLLC/administrate_exportable#12]
How to filter data before export based on custom scoped_resource?

**Comment by andreibondarev** [comment]
@rslhdyt Could you please elaborate on this question? Are you referring to the new `administrate v0.12.0` collection filters?

**Comment by rslhdyt** [comment]
Hi @andreibondarev 

No, in my case. I just want to filter the export result when using scoped_resource.
this is the sample code.

```
module Admin
  class UsersController < Admin::ApplicationController
    include AdministrateExportable::Exporter

    def scoped_resource
      resource_class.where(is_active: true)
    end
  end
end
```

in my index page, the only active user will show but when I click the export button all users exported to csv.

**Comment by andreibondarev** [comment]
@rslhdyt Got it, that's valid. Would you like to take a stab at a pull request for this?

**Comment by andreibondarev** [comment]
@rslhdyt Just released a new version that takes in the filters and scoped_resource. Please try it out!

**Comment by rslhdyt** [comment]
@andreibondarev I am very sorry I just read your reply. thank you for the update, I really appreciate it.
