### ISSUE TITLE
Undefined method `collection_includes'

### ISSUE THREAD

**Issue by dyerc** [SourceLabsLLC/administrate_exportable#13]
I have just been following the readme to setup administrate_exportable with an administrate 0.11.0 installation. I'm getting the following error after clicking the export button:

```
NoMethodError (undefined method `collection_includes' for #<PlayerDashboard:0x00007ffb7d0d93c0>
Did you mean?  collection_attributes):

administrate_exportable (0.1.2) lib/administrate_exportable/exporter_service.rb:84:in `collection'
administrate_exportable (0.1.2) lib/administrate_exportable/exporter_service.rb:19:in `block in csv'
/Users/Chris/.rbenv/versions/2.4.5/lib/ruby/2.4.0/csv.rb:1183:in `generate'
administrate_exportable (0.1.2) lib/administrate_exportable/exporter_service.rb:15:in `csv'
administrate_exportable (0.1.2) lib/administrate_exportable/exporter_service.rb:6:in `csv'
administrate_exportable (0.1.2) lib/administrate_exportable/exporter.rb:12:in `block in exportable'
actionpack (5.2.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
```

I have added the include line to my controller and my controller starts as follows:
```
class PlayersController < Admin::ApplicationController
    include AdministrateExportable::Exporter
```

**Comment by tuxtux59** [comment]
Hi,
I face the same problem today.

My workaround was to rewrite `AdministrateExportable::ExporterService#collection` in an initializer Like so:
```ruby
require 'administrate/base_dashboard'
AdministrateExportable::ExporterService.class_eval do
  def collection
    # code your stuff here like resource_includes = []
  end
end
```

**Comment by andreibondarev** [comment]
@tuxtux59 What version of this gem are you running?

**Comment by dyerc** [comment]
@andreibondarev thanks for the update. I've just upgraded to version 0.1.3 but the problem persists, albeit with a slightly different error this time:

```
NoMethodError (undefined method `apply_collection_includes' for #<Admin::PlayersController:0x000055dbb256b060>
Did you mean?  apply_resource_includes):
 administrate_exportable (0.1.3) lib/administrate_exportable/exporter.rb:16:in `block in exportable'
[f8b0cb20-67c3-4879-a1fd-8d0f6e056832] actionpack (5.2.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
```

**Comment by dyerc** [comment]
I just looked into this again and your solution @andreibondarev works perfectly but only in `administrate (0.12.0)`. 

When I compared this [administrate file](https://github.com/thoughtbot/administrate/blob/master/app/controllers/administrate/application_controller.rb) between the 0.11.0 and 0.12.0 tags it looks as though they changed `apply_resource_includes` to become `apply_collection_includes`. Maybe to properly close this issue it would be best to set a dependency in the gemspec to require 0.12.0

**Comment by andreibondarev** [comment]
@dyerc Would you like to submit a PR?

**Comment by dyerc** [comment]
Yes no problem. Would you prefer 0.1.4 or 0.2.0 since it's not backwards compatible?

**Comment by andreibondarev** [comment]
@dyerc `0.2.0` sounds right.

**Comment by andreibondarev** [comment]
@dyerc Thank you for the fix! Releasing a new gem version shortly.
