### ISSUE TITLE
Broken pagination with administrate-0.15.0

### ISSUE THREAD

**Issue by dmitryzuev** [SourceLabsLLC/administrate_exportable#35]
## Problem
Administrate gem changed pagination param name from `page` to `_page`

https://github.com/thoughtbot/administrate/blob/master/app/views/administrate/application/index.html.erb#L65
```ruby
<%= paginate resources, param_name: '_page' %>
```

## Solution
Update [this view](https://github.com/SourceLabsLLC/administrate_exportable/blob/master/app/views/admin/application/index.html.erb#L66) to pass correct `param_name`

**Comment by andreibondarev** [comment]
@dmitryzuev Thank you for filing an issue here. Would you please be able to issue a PR to get it fixed? I can get it reviewed, merged, and cut a new release tag shortly thereafter. Thanks!

**Comment by dmitryzuev** [comment]
@andreibondarev sure, #36

**Comment by iamnader** [comment]
@andreibondarev can you please merge?  thank you!

**Comment by yourivdlans** [comment]
Thanks for this change! Would it also be possible to release a new version of the gem?
