### ISSUE TITLE
Error: Please use symbols for polymorphic route arguments.

### ISSUE THREAD

**Issue by esmyllyaho90** [SourceLabsLLC/administrate_exportable#44]
ArgumentError Please use symbols for polymorphic route arguments.

I get this error trying to manually add the button example code from your docs:

```
<div>
  <%= link_to(
    'Export',
    [:export, namespace, page.resource_name.to_s.pluralize, sanitized_order_params(page, :id).to_h.merge(format: :csv)],
    class: 'button'
  ) if valid_action?(:export) %>
</div>
```

I'm using:
administrate 0.17
administrate_exportable 0.5
rails 7.0.1
ruby 3.0.3

**Comment by andreibondarev** [comment]
@esmyllyaho90 I went ahead and updated the examples in the [README](https://github.com/SourceLabsLLC/administrate_exportable/blob/master/README.md#usage).

**Comment by esmyllyaho90** [comment]
> @esmyllyaho90 I went ahead and updated the examples in the [README](https://github.com/SourceLabsLLC/administrate_exportable/blob/master/README.md#usage).

Awesome, thank you :)
